version: "3"

services:
  # database containers, one for each db
  pg_fixPermissions:
    image: "bitnami/postgresql:14"
    user: root
    command: chown -R 1001:1001 /bitnami/postgresql
    volumes:
      - ".data/pg:/bitnami/postgresql/data"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: "api"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3100:3100"
    volumes:
      - .data/.wwebjs_auth:/app/.wwebjs_auth
      - .data/medias:/app/public
